// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDljh-0fDXymds4HpeoYzsNxe_jY-UpmZ4',
//     appId: '1:656403595694:web:4800e9bda842bc93c0083f',
//     messagingSenderId: '656403595694',
//     projectId: 'MissionVardi',
//     authDomain: 'MissionVardi.firebaseapp.com',
//     storageBucket: 'MissionVardi.firebasestorage.app',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAPm35W3RM-COgQSArPxhQhBKflHfZCKNo',
//     appId: '1:656403595694:android:a85cac861b1eab09c0083f',
//     messagingSenderId: '656403595694',
//     projectId: 'MissionVardi',
//     storageBucket: 'MissionVardi.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD3aYdx9S4IWjxFoc2x1q2jLki_1LwvMA8',
//     appId: '1:656403595694:ios:fe2b5b24d9efc2fcc0083f',
//     messagingSenderId: '656403595694',
//     projectId: 'MissionVardi',
//     storageBucket: 'MissionVardi.firebasestorage.app',
//     iosBundleId: 'com.example.khrishiWings',
//   );
// }
