// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP1bBz70j5zmHF7WROsm-PuJ6GR0xJiwg',
    appId: '1:274263956432:web:8c3e922d8c1ca5cebc37d5',
    messagingSenderId: '274263956432',
    projectId: 'mission-vardi-d1b3b',
    authDomain: 'mission-vardi-d1b3b.firebaseapp.com',
    storageBucket: 'mission-vardi-d1b3b.firebasestorage.app',
    measurementId: 'G-19EWTV9N3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmGiZCGukfM--2FJMB_9Oi1ylGJODT9Do',
    appId: '1:274263956432:android:1496e3c97ecc7deebc37d5',
    messagingSenderId: '274263956432',
    projectId: 'mission-vardi-d1b3b',
    storageBucket: 'mission-vardi-d1b3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlQJTHdDf-0GT4GIvLh7xhPTEXubGZKXA',
    appId: '1:274263956432:ios:5239563b6882c04bbc37d5',
    messagingSenderId: '274263956432',
    projectId: 'mission-vardi-d1b3b',
    storageBucket: 'mission-vardi-d1b3b.firebasestorage.app',
    androidClientId: '274263956432-3cbe6r9n7ef58bv7n5hpd4of30v3hnhl.apps.googleusercontent.com',
    iosClientId: '274263956432-0ocoiu8k5bffcq594fk3k9skfapusuaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.khrishiWings',
  );
}
