import { MainCategory, SubCategory, MockTest } from '../src/types';

export const initialMainCategories: MainCategory[] = [
  {
    id: 'cat_maha_state',
    name: 'Maharashtra State Exams',
    nameMarathi: 'महाराष्ट्र राज्यस्तरीय स्पर्धा परीक्षा',
    marathiName: 'महाराष्ट्र राज्यस्तरीय स्पर्धा परीक्षा',
    slug: 'maharashtra-state-exams',
    description: 'MPSC Rajyaseva, Police Bharti, Talathi, Zilla Parishad, Arogya Vibhag & Saral Seva exams.',
    icon: 'Shield',
    badge: 'Most Popular',
    order: 1,
    status: 'active',
  },
  {
    id: 'cat_bank_ins',
    name: 'Bank & Insurance',
    nameMarathi: 'बँकिंग व विमा भरती परीक्षा',
    marathiName: 'बँकिंग व विमा भरती परीक्षा',
    slug: 'bank-and-insurance',
    description: 'SBI PO & Clerk, IBPS PO/Clerk, IBPS RRB, RBI Assistant & Insurance exams.',
    icon: 'Landmark',
    badge: 'TCS/IBPS',
    order: 2,
    status: 'active',
  },
  {
    id: 'cat_ssc',
    name: 'SSC Exams',
    nameMarathi: 'कर्मचारी निवड आयोग (SSC)',
    marathiName: 'कर्मचारी निवड आयोग (SSC)',
    slug: 'ssc-exams',
    description: 'SSC CGL, CHSL, GD Constable, MTS, CPO Sub-Inspector & Stenographer test series.',
    icon: 'Award',
    badge: 'Central Govt',
    order: 3,
    status: 'active',
  },
  {
    id: 'cat_railways',
    name: 'Railways Exams',
    nameMarathi: 'रेल्वे भरती बोर्ड (RRB)',
    marathiName: 'रेल्वे भरती बोर्ड (RRB)',
    slug: 'railways-exams',
    description: 'RRB NTPC, Group D, ALP & Technician, Junior Engineer CBT mock tests.',
    icon: 'Train',
    badge: 'CBT Mode',
    order: 4,
    status: 'active',
  },
  {
    id: 'cat_teaching',
    name: 'Teaching Exams',
    nameMarathi: 'शिक्षक भरती व पात्रता परीक्षा (TET/TAIT)',
    marathiName: 'शिक्षक भरती व पात्रता परीक्षा (TET/TAIT)',
    slug: 'teaching-exams',
    description: 'Maharashtra MahaTET Paper 1 & 2, TAIT Aptitude & Intelligence, CTET preparation.',
    icon: 'GraduationCap',
    badge: 'MahaTET/TAIT',
    order: 5,
    status: 'active',
  },
  {
    id: 'cat_subject_special',
    name: 'Subject-Wise & Special Test',
    nameMarathi: 'विषयनिहाय व विशेष सराव चाचण्या',
    marathiName: 'विषयनिहाय व विशेष सराव चाचण्या',
    slug: 'subject-wise-special-test',
    description: 'Special topic drills for Marathi Grammar, Maths, Reasoning, Polity, Geography & English.',
    icon: 'Sparkles',
    badge: 'High Yield',
    order: 6,
    status: 'active',
  },
];

export const initialSubCategories: SubCategory[] = [
  // 1. Under Maharashtra State Exams
  {
    id: 'sub_mpsc',
    mainCategoryId: 'cat_maha_state',
    mainCategoryName: 'Maharashtra State Exams',
    name: 'MPSC राज्यसेवा व गट-ब, गट-क',
    nameMarathi: 'MPSC राज्यसेवा व संयुक्त गट-ब, गट-क पूर्व-मुख्य',
    marathiName: 'MPSC राज्यसेवा व संयुक्त गट-ब, गट-क पूर्व-मुख्य',
    slug: 'mpsc-rajyaseva-combine',
    description: 'State Services, PSI, STI, ASO, Excise SI, Tax Assistant, Clerk Typist test series.',
    icon: 'GraduationCap',
    badge: 'MPSC Pattern',
    status: 'active',
  },
  {
    id: 'sub_police_bharti',
    mainCategoryId: 'cat_maha_state',
    mainCategoryName: 'Maharashtra State Exams',
    name: 'महाराष्ट्र पोलीस भरती',
    nameMarathi: 'महाराष्ट्र पोलीस शिपाई, चालक व SRPF भरती',
    marathiName: 'महाराष्ट्र पोलीस शिपाई, चालक व SRPF भरती',
    slug: 'maharashtra-police-bharti',
    description: 'Constable, SRPF, Jail Warder, Driver Police CBT written test series & physical guide.',
    icon: 'Shield',
    badge: 'Mission Vardi',
    status: 'active',
  },
  {
    id: 'sub_talathi_bharti',
    mainCategoryId: 'cat_maha_state',
    mainCategoryName: 'Maharashtra State Exams',
    name: 'तलाठी भरती परीक्षा (TCS/IBPS)',
    nameMarathi: 'महसूल विभाग तलाठी भरती परीक्षा',
    marathiName: 'महसूल विभाग तलाठी भरती परीक्षा',
    slug: 'talathi-bharti-tcs-ibps',
    description: 'Revenue department Talathi full length & sectional TCS pattern tests.',
    icon: 'FileText',
    badge: 'TCS Pattern',
    status: 'active',
  },
  {
    id: 'sub_zilla_parishad',
    mainCategoryId: 'cat_maha_state',
    mainCategoryName: 'Maharashtra State Exams',
    name: 'जिल्हा परिषद व ग्रामसेवक',
    nameMarathi: 'जिल्हा परिषद, ग्रामसेवक व आरोग्य सेवक भरती',
    marathiName: 'जिल्हा परिषद, ग्रामसेवक व आरोग्य सेवक भरती',
    slug: 'zp-gramsevak-bharti',
    description: 'Gramsevak, Arogya Sevak/Sevika, Krushi Sevak, Junior Engineer & Clerk tests.',
    icon: 'Building2',
    badge: 'IBPS Pattern',
    status: 'active',
  },
  {
    id: 'sub_arogya_railway',
    mainCategoryId: 'cat_maha_state',
    mainCategoryName: 'Maharashtra State Exams',
    name: 'आरोग्य विभाग व तांत्रिक भरती',
    nameMarathi: 'सार्वजनिक आरोग्य विभाग गट-क व गट-ड भरती',
    marathiName: 'सार्वजनिक आरोग्य विभाग गट-क व गट-ड भरती',
    slug: 'arogya-vibhag-technical',
    description: 'Public Health department technical & non-technical staff recruitment mock tests.',
    icon: 'HeartPulse',
    badge: 'Technical',
    status: 'active',
  },
  {
    id: 'sub_vanrakshak',
    mainCategoryId: 'cat_maha_state',
    mainCategoryName: 'Maharashtra State Exams',
    name: 'वनरक्षक व वनविभाग भरती',
    nameMarathi: 'महाराष्ट्र वन विभाग वनरक्षक भरती',
    marathiName: 'महाराष्ट्र वन विभाग वनरक्षक भरती',
    slug: 'vanrakshak-forest-guard',
    description: 'Forest Guard, Surveyor, Accountant recruitment mock tests & environment topics.',
    icon: 'TreePine',
    badge: 'Forest Dept',
    status: 'active',
  },

  // 2. Under Bank & Insurance
  {
    id: 'sub_bank_ibps_po',
    mainCategoryId: 'cat_bank_ins',
    mainCategoryName: 'Bank & Insurance',
    name: 'IBPS PO & Clerk (Prelims + Mains)',
    nameMarathi: 'आयबीपीएस पीओ व लिपिक परीक्षा',
    slug: 'ibps-po-clerk',
    description: 'Quantitative aptitude, reasoning, English, computer and banking awareness tests.',
    icon: 'Landmark',
    badge: 'IBPS',
    status: 'active',
  },
  {
    id: 'sub_bank_sbi',
    mainCategoryId: 'cat_bank_ins',
    mainCategoryName: 'Bank & Insurance',
    name: 'SBI PO & Junior Associate',
    nameMarathi: 'स्टेट बँक ऑफ इंडिया पीओ व लिपिक',
    slug: 'sbi-po-clerk',
    description: 'High difficulty bank mock series tailored for State Bank of India recruitment.',
    icon: 'CreditCard',
    badge: 'SBI',
    status: 'active',
  },
  {
    id: 'sub_bank_rrb',
    mainCategoryId: 'cat_bank_ins',
    mainCategoryName: 'Bank & Insurance',
    name: 'IBPS RRB Gramin Bank Officer & Assistant',
    nameMarathi: 'ग्रामीण बँक अधिकारी व सहाय्यक परीक्षा',
    slug: 'ibps-rrb-officer-assistant',
    description: 'Bilingual regional rural bank exam series with Marathi & English support.',
    icon: 'Compass',
    badge: 'Gramin Bank',
    status: 'active',
  },

  // 3. Under SSC Exams
  {
    id: 'sub_ssc_cgl',
    mainCategoryId: 'cat_ssc',
    mainCategoryName: 'SSC Exams',
    name: 'SSC CGL (Tier 1 & Tier 2)',
    nameMarathi: 'एसएससी सीजीएल पूर्व व मुख्य परीक्षा',
    slug: 'ssc-cgl-tier-1-2',
    description: 'Combined Graduate Level mock papers with detailed solutions and analytics.',
    icon: 'Award',
    badge: 'Graduate Level',
    status: 'active',
  },
  {
    id: 'sub_ssc_chsl',
    mainCategoryId: 'cat_ssc',
    mainCategoryName: 'SSC Exams',
    name: 'SSC CHSL (10+2 Level)',
    nameMarathi: 'एसएससी सीएचएसएल १२ वी स्तर परीक्षा',
    slug: 'ssc-chsl-10-plus-2',
    description: 'LDC, JSA and DEO level comprehensive test series.',
    icon: 'FileSpreadsheet',
    badge: '10+2 Level',
    status: 'active',
  },
  {
    id: 'sub_ssc_gd',
    mainCategoryId: 'cat_ssc',
    mainCategoryName: 'SSC Exams',
    name: 'SSC GD Constable (BSF, CISF, CRPF)',
    nameMarathi: 'एसएससी जीडी कॉन्स्टेबल भरती परीक्षा',
    slug: 'ssc-gd-constable',
    description: 'General Duty Constable central armed police forces test series in Marathi & Hindi.',
    icon: 'ShieldAlert',
    badge: 'Armed Forces',
    status: 'active',
  },

  // 4. Under Railways Exams
  {
    id: 'sub_rrb_ntpc',
    mainCategoryId: 'cat_railways',
    mainCategoryName: 'Railways Exams',
    name: 'RRB NTPC (Non-Technical Popular Categories)',
    nameMarathi: 'रेल्वे भरती बोर्ड एनटीपीसी सीबीटी १ व २',
    slug: 'rrb-ntpc-cbt-1-2',
    description: 'Station Master, Goods Guard, Commercial Apprentice test series.',
    icon: 'Train',
    badge: 'NTPC',
    status: 'active',
  },
  {
    id: 'sub_rrb_groupd',
    mainCategoryId: 'cat_railways',
    mainCategoryName: 'Railways Exams',
    name: 'RRB Group D (Level 1 Posts)',
    nameMarathi: 'रेल्वे गट-ड (लेव्हल १) परीक्षा',
    slug: 'rrb-group-d-level-1',
    description: 'Track Maintainer, Pointsman & Assistant workshop full syllabus test papers.',
    icon: 'Wrench',
    badge: 'Group D',
    status: 'active',
  },

  // 5. Under Teaching Exams
  {
    id: 'sub_maha_tet',
    mainCategoryId: 'cat_teaching',
    mainCategoryName: 'Teaching Exams',
    name: 'MahaTET Paper 1 & Paper 2',
    nameMarathi: 'महाराष्ट्र शिक्षक पात्रता परीक्षा (MahaTET)',
    slug: 'mahatet-paper-1-2',
    description: 'Child Development, Pedagogy, Language 1 (Marathi), Maths & Social Sciences.',
    icon: 'BookOpen',
    badge: 'MahaTET',
    status: 'active',
  },
  {
    id: 'sub_tait',
    mainCategoryId: 'cat_teaching',
    mainCategoryName: 'Teaching Exams',
    name: 'TAIT (Teacher Aptitude & Intelligence Test)',
    nameMarathi: 'पवित्र पोर्टल शिक्षक अभियोग्यता व बुद्धिमत्ता चाचणी',
    slug: 'tait-aptitude-intelligence',
    description: '200 Marks comprehensive speed and accuracy exam tests for school teachers.',
    icon: 'Brain',
    badge: 'TAIT',
    status: 'active',
  },

  // 6. Under Subject-Wise & Special Test
  {
    id: 'sub_special_marathi',
    mainCategoryId: 'cat_subject_special',
    mainCategoryName: 'Subject-Wise & Special Test',
    name: 'मराठी व्याकरण व शब्दसंग्रह स्पेशल',
    nameMarathi: 'मराठी व्याकरण, म्हणी व समानार्थी शब्द',
    slug: 'marathi-vyakaran-special',
    description: 'Full coverage of Marathi grammar for MPSC, Police, Talathi and all state exams.',
    icon: 'Languages',
    badge: '100% Marathi',
    status: 'active',
  },
  {
    id: 'sub_special_maths',
    mainCategoryId: 'cat_subject_special',
    mainCategoryName: 'Subject-Wise & Special Test',
    name: 'अंकगणित व गणित सराव (Quantitative Aptitude)',
    nameMarathi: 'अंकगणित, संख्याज्ञान व शॉर्टकट ट्रिक्स',
    slug: 'quantitative-aptitude-special',
    description: 'Percentages, Profit & Loss, Speed-Time-Distance, Averages and Number Series.',
    icon: 'Calculator',
    badge: 'Maths Special',
    status: 'active',
  },
  {
    id: 'sub_special_reasoning',
    mainCategoryId: 'cat_subject_special',
    mainCategoryName: 'Subject-Wise & Special Test',
    name: 'बुद्धिमत्ता चाचणी व तार्किक क्षमता',
    nameMarathi: 'तार्किक विचार, सांकेतिक भाषा व नातेसंबंध',
    slug: 'reasoning-ability-special',
    description: 'Analogies, Syllogisms, Coding-Decoding, Seating Arrangements and Logic.',
    icon: 'Brain',
    badge: 'Reasoning',
    status: 'active',
  },
  {
    id: 'sub_special_polity',
    mainCategoryId: 'cat_subject_special',
    mainCategoryName: 'Subject-Wise & Special Test',
    name: 'भारतीय संविधान, पंचायत राज व पोलीस कायदा',
    nameMarathi: 'राज्यघटना, मूलभूत अधिकार व पोलीस कायदे',
    slug: 'indian-polity-police-law',
    description: 'Articles, Amendments, Judiciary, Panchayati Raj and Maharashtra Police Act.',
    icon: 'Scroll',
    badge: 'Polity & Law',
    status: 'active',
  },
];
