import { MockTest } from '../src/types';

export const userProvidedMockTests: MockTest[] = [
  // 1. Maharashtra Police Bharti - Maths
  {
    id: 'quiz_sub_pb_maths_1',
    title: 'अंकगणित व गणित सराव - सराव चाचणी #1',
    titleMarathi: 'अंकगणित व गणित सराव - सराव चाचणी #1',
    description: 'महाराष्ट्र पोलीस भरती अंतर्गत अंकगणित व गणित सराव विषयावर आधारित परिपूर्ण TCS/IBPS पॅटर्न चाचणी संच #1.',
    mainCategoryId: 'cat_maha_state',
    mainCategoryName: 'Maharashtra State Exams',
    subCategoryId: 'sub_police_bharti',
    subCategoryName: 'महाराष्ट्र पोलीस भरती',
    main_category_id: 'cat_maha_state',
    sub_category_id: 'sub_police_bharti',
    examId: 'exam-police',
    examName: 'Police Bharti',
    categoryId: 'cat-police-constable',
    categoryName: 'पोलीस शिपाई भरती',
    category: 'महाराष्ट्र पोलीस भरती',
    access_type: 'free',
    isFree: true,
    price: 0,
    includeInPackage: true,
    packageName: 'Maharashtra Police Bharti All-in-One Series',
    durationMinutes: 30,
    totalMarks: 50,
    totalQuestions: 5,
    passingMarks: 20,
    negativeMarking: 0.25,
    difficulty: 'Medium',
    language: 'Marathi',
    rating: 4.9,
    reviewsCount: 135,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=500&q=80',
    type: 'practice',
    questionIds: ['q-5', 'q-13', 'q-14', 'q-1', 'q-7'],
    attemptsCount: 1450,
    createdAt: '2026-08-29T12:03:56Z',
  },
  {
    id: 'quiz_sub_pb_maths_2',
    title: 'अंकगणित व गणित सराव - सराव चाचणी #2',
    titleMarathi: 'अंकगणित व गणित सराव - सराव चाचणी #2',
    description: 'महाराष्ट्र पोलीस भरती अंतर्गत अंकगणित व गणित सराव विषयावर आधारित परिपूर्ण TCS/IBPS पॅटर्न चाचणी संच #2.',
    mainCategoryId: 'cat_maha_state',
    mainCategoryName: 'Maharashtra State Exams',
    subCategoryId: 'sub_police_bharti',
    subCategoryName: 'महाराष्ट्र पोलीस भरती',
    main_category_id: 'cat_maha_state',
    sub_category_id: 'sub_police_bharti',
    examId: 'exam-police',
    examName: 'Police Bharti',
    categoryId: 'cat-police-constable',
    category: 'महाराष्ट्र पोलीस भरती',
    access_type: 'free',
    isFree: true,
    price: 0,
    includeInPackage: true,
    durationMinutes: 30,
    totalMarks: 50,
    totalQuestions: 5,
    passingMarks: 20,
    negativeMarking: 0.25,
    difficulty: 'Medium',
    language: 'Marathi',
    rating: 5.0,
    reviewsCount: 150,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=500&q=80',
    type: 'practice',
    questionIds: ['q-5', 'q-13', 'q-14', 'q-2', 'q-8'],
    attemptsCount: 980,
    createdAt: '2026-08-29T12:03:57Z',
  },
  {
    id: 'quiz_sub_pb_maths_3',
    title: 'अंकगणित व गणित सराव - सराव चाचणी #3 (Paid Individual)',
    titleMarathi: 'अंकगणित व गणित सराव - सराव चाचणी #3',
    description: 'महाराष्ट्र पोलीस भरती अंतर्गत अंकगणित व गणित सराव विषयावर आधारित परिपूर्ण TCS/IBPS पॅटर्न चाचणी संच #3.',
    mainCategoryId: 'cat_maha_state',
    mainCategoryName: 'Maharashtra State Exams',
    subCategoryId: 'sub_police_bharti',
    subCategoryName: 'महाराष्ट्र पोलीस भरती',
    main_category_id: 'cat_maha_state',
    sub_category_id: 'sub_police_bharti',
    examId: 'exam-police',
    examName: 'Police Bharti',
    categoryId: 'cat-police-constable',
    category: 'महाराष्ट्र पोलीस भरती',
    access_type: 'paid',
    isFree: false,
    price: 49,
    discountPrice: 99,
    includeInPackage: true,
    packageName: 'Police Bharti Premium Super 50 Pack',
    durationMinutes: 30,
    totalMarks: 50,
    totalQuestions: 5,
    passingMarks: 20,
    negativeMarking: 0.25,
    difficulty: 'Medium',
    language: 'Marathi',
    rating: 4.8,
    reviewsCount: 165,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=500&q=80',
    type: 'practice',
    questionIds: ['q-5', 'q-13', 'q-14', 'q-3', 'q-9'],
    attemptsCount: 620,
    createdAt: '2026-08-29T12:03:57Z',
  },
  {
    id: 'quiz_sub_pb_maths_5',
    title: 'अंकगणित व गणित सराव - सराव चाचणी #5 (MPSC & Police Level)',
    titleMarathi: 'अंकगणित व गणित सराव - सराव चाचणी #5',
    description: 'महाराष्ट्र पोलीस भरती अंतर्गत अंकगणित व गणित सराव विषयावर आधारित परिपूर्ण TCS/IBPS पॅटर्न चाचणी संच #5.',
    mainCategoryId: 'cat_maha_state',
    mainCategoryName: 'Maharashtra State Exams',
    subCategoryId: 'sub_police_bharti',
    subCategoryName: 'महाराष्ट्र पोलीस भरती',
    main_category_id: 'cat_maha_state',
    sub_category_id: 'sub_police_bharti',
    examId: 'exam-police',
    examName: 'Police Bharti',
    categoryId: 'cat-police-constable',
    category: 'महाराष्ट्र पोलीस भरती',
    access_type: 'paid',
    isFree: false,
    price: 149,
    discountPrice: 299,
    includeInPackage: true,
    packageName: 'Mission Vardi Full Mock Series 2026',
    durationMinutes: 30,
    totalMarks: 50,
    totalQuestions: 5,
    passingMarks: 20,
    negativeMarking: 0.25,
    difficulty: 'MPSC Level',
    language: 'Marathi',
    rating: 5.0,
    reviewsCount: 195,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=500&q=80',
    type: 'practice',
    questionIds: ['q-5', 'q-13', 'q-14', 'q-4', 'q-10'],
    attemptsCount: 450,
    createdAt: '2026-08-29T12:03:57Z',
  },

  // 2. Police Bharti - Reasoning
  {
    id: 'quiz_sub_pb_reasoning_1',
    title: 'बुद्धिमत्ता चाचणी - सराव चाचणी #1',
    titleMarathi: 'बुद्धिमत्ता चाचणी - सराव चाचणी #1',
    description: 'महाराष्ट्र पोलीस भरती अंतर्गत बुद्धिमत्ता चाचणी विषयावर आधारित परिपूर्ण TCS/IBPS पॅटर्न चाचणी संच #1.',
    mainCategoryId: 'cat_maha_state',
    mainCategoryName: 'Maharashtra State Exams',
    subCategoryId: 'sub_police_bharti',
    subCategoryName: 'महाराष्ट्र पोलीस भरती',
    main_category_id: 'cat_maha_state',
    sub_category_id: 'sub_police_bharti',
    examId: 'exam-police',
    examName: 'Police Bharti',
    category: 'महाराष्ट्र पोलीस भरती',
    access_type: 'free',
    isFree: true,
    price: 0,
    includeInPackage: true,
    durationMinutes: 30,
    totalMarks: 50,
    totalQuestions: 5,
    passingMarks: 20,
    negativeMarking: 0.25,
    difficulty: 'Medium',
    language: 'Marathi',
    rating: 4.9,
    reviewsCount: 135,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=500&q=80',
    type: 'practice',
    questionIds: ['q-7', 'q-8', 'q-14', 'q-2', 'q-4'],
    attemptsCount: 1200,
    createdAt: '2026-08-29T12:03:57Z',
  },
  {
    id: 'quiz_sub_pb_reasoning_3',
    title: 'बुद्धिमत्ता चाचणी - सराव चाचणी #3',
    titleMarathi: 'बुद्धिमत्ता चाचणी - सराव चाचणी #3',
    description: 'महाराष्ट्र पोलीस भरती अंतर्गत बुद्धिमत्ता चाचणी विषयावर आधारित परिपूर्ण TCS/IBPS पॅटर्न चाचणी संच #3.',
    mainCategoryId: 'cat_maha_state',
    mainCategoryName: 'Maharashtra State Exams',
    subCategoryId: 'sub_police_bharti',
    subCategoryName: 'महाराष्ट्र पोलीस भरती',
    main_category_id: 'cat_maha_state',
    sub_category_id: 'sub_police_bharti',
    examId: 'exam-police',
    examName: 'Police Bharti',
    category: 'महाराष्ट्र पोलीस भरती',
    access_type: 'paid',
    isFree: false,
    price: 49,
    discountPrice: 99,
    includeInPackage: true,
    durationMinutes: 30,
    totalMarks: 50,
    totalQuestions: 5,
    passingMarks: 20,
    negativeMarking: 0.25,
    difficulty: 'Medium',
    language: 'Marathi',
    rating: 4.8,
    reviewsCount: 165,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=500&q=80',
    type: 'practice',
    questionIds: ['q-7', 'q-8', 'q-14', 'q-3', 'q-5'],
    attemptsCount: 540,
    createdAt: '2026-08-29T12:03:57Z',
  },

  // 3. Police Bharti - Marathi Grammar
  {
    id: 'quiz_sub_pb_marathi_1',
    title: 'मराठी व्याकरण व शब्दसंग्रह - सराव चाचणी #1',
    titleMarathi: 'मराठी व्याकरण व शब्दसंग्रह - सराव चाचणी #1',
    description: 'महाराष्ट्र पोलीस भरती अंतर्गत मराठी व्याकरण व शब्दसंग्रह विषयावर आधारित परिपूर्ण TCS/IBPS पॅटर्न चाचणी संच #1.',
    mainCategoryId: 'cat_maha_state',
    mainCategoryName: 'Maharashtra State Exams',
    subCategoryId: 'sub_police_bharti',
    subCategoryName: 'महाराष्ट्र पोलीस भरती',
    main_category_id: 'cat_maha_state',
    sub_category_id: 'sub_police_bharti',
    examId: 'exam-police',
    examName: 'Police Bharti',
    category: 'महाराष्ट्र पोलीस भरती',
    access_type: 'free',
    isFree: true,
    price: 0,
    includeInPackage: true,
    durationMinutes: 30,
    totalMarks: 50,
    totalQuestions: 5,
    passingMarks: 20,
    negativeMarking: 0.25,
    difficulty: 'Medium',
    language: 'Marathi',
    rating: 4.9,
    reviewsCount: 135,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=500&q=80',
    type: 'practice',
    questionIds: ['q-1', 'q-2', 'q-3', 'q-4', 'q-5'],
    attemptsCount: 1780,
    createdAt: '2026-08-29T12:03:57Z',
  },

  // 4. Talathi Bharti (TCS/IBPS)
  {
    id: 'quiz_sub_tb_marathi_1',
    title: 'तलाठी मराठी भाषा अभ्यास - सराव चाचणी #1',
    titleMarathi: 'तलाठी मराठी भाषा अभ्यास - सराव चाचणी #1',
    description: 'तलाठी भरती परीक्षा (TCS/IBPS) अंतर्गत तलाठी मराठी भाषा अभ्यास विषयावर आधारित परिपूर्ण TCS/IBPS पॅटर्न चाचणी संच #1.',
    mainCategoryId: 'cat_maha_state',
    mainCategoryName: 'Maharashtra State Exams',
    subCategoryId: 'sub_talathi_bharti',
    subCategoryName: 'तलाठी भरती परीक्षा (TCS/IBPS)',
    main_category_id: 'cat_maha_state',
    sub_category_id: 'sub_talathi_bharti',
    examId: 'exam-talathi',
    examName: 'Talathi Bharti',
    category: 'तलाठी भरती परीक्षा (TCS/IBPS)',
    access_type: 'free',
    isFree: true,
    price: 0,
    includeInPackage: true,
    packageName: 'Maharashtra Talathi TCS/IBPS Master Pass',
    durationMinutes: 30,
    totalMarks: 50,
    totalQuestions: 5,
    passingMarks: 20,
    negativeMarking: 0.25,
    difficulty: 'Medium',
    language: 'Marathi',
    rating: 4.9,
    reviewsCount: 135,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=500&q=80',
    type: 'practice',
    questionIds: ['q-1', 'q-2', 'q-3', 'q-4', 'q-9'],
    attemptsCount: 2100,
    createdAt: '2026-08-29T12:03:59Z',
  },
  {
    id: 'quiz_sub_tb_marathi_3',
    title: 'तलाठी मराठी भाषा अभ्यास - सराव चाचणी #3',
    titleMarathi: 'तलाठी मराठी भाषा अभ्यास - सराव चाचणी #3',
    description: 'तलाठी भरती परीक्षा (TCS/IBPS) अंतर्गत तलाठी मराठी भाषा अभ्यास विषयावर आधारित परिपूर्ण TCS/IBPS पॅटर्न चाचणी संच #3.',
    mainCategoryId: 'cat_maha_state',
    mainCategoryName: 'Maharashtra State Exams',
    subCategoryId: 'sub_talathi_bharti',
    subCategoryName: 'तलाठी भरती परीक्षा (TCS/IBPS)',
    main_category_id: 'cat_maha_state',
    sub_category_id: 'sub_talathi_bharti',
    examId: 'exam-talathi',
    examName: 'Talathi Bharti',
    category: 'तलाठी भरती परीक्षा (TCS/IBPS)',
    access_type: 'paid',
    isFree: false,
    price: 49,
    discountPrice: 99,
    includeInPackage: true,
    durationMinutes: 30,
    totalMarks: 50,
    totalQuestions: 5,
    passingMarks: 20,
    negativeMarking: 0.25,
    difficulty: 'Medium',
    language: 'Marathi',
    rating: 4.8,
    reviewsCount: 165,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=500&q=80',
    type: 'practice',
    questionIds: ['q-1', 'q-2', 'q-3', 'q-4', 'q-10'],
    attemptsCount: 890,
    createdAt: '2026-08-29T12:03:59Z',
  },

  // 5. MPSC Rajyaseva & Combined
  {
    id: 'quiz_sub_mpsc_polity_1',
    title: 'भारतीय संविधान व राज्यव्यवस्था - सराव चाचणी #1',
    titleMarathi: 'भारतीय संविधान व राज्यव्यवस्था - सराव चाचणी #1',
    description: 'MPSC राज्यसेवा व गट-ब, गट-क अंतर्गत भारतीय संविधान व राज्यव्यवस्था विषयावर आधारित परिपूर्ण TCS/IBPS पॅटर्न चाचणी संच #1.',
    mainCategoryId: 'cat_maha_state',
    mainCategoryName: 'Maharashtra State Exams',
    subCategoryId: 'sub_mpsc',
    subCategoryName: 'MPSC राज्यसेवा व गट-ब, गट-क',
    main_category_id: 'cat_maha_state',
    sub_category_id: 'sub_mpsc',
    examId: 'exam-mpsc',
    examName: 'MPSC',
    category: 'MPSC राज्यसेवा व गट-ब, गट-क',
    access_type: 'free',
    isFree: true,
    price: 0,
    includeInPackage: true,
    packageName: 'MPSC Rajyaseva GS Prelims Test Pack',
    durationMinutes: 30,
    totalMarks: 50,
    totalQuestions: 5,
    passingMarks: 20,
    negativeMarking: 0.25,
    difficulty: 'Medium',
    language: 'Marathi',
    rating: 4.9,
    reviewsCount: 135,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=500&q=80',
    type: 'practice',
    questionIds: ['q-10', 'q-3', 'q-15', 'q-1', 'q-2'],
    attemptsCount: 3100,
    createdAt: '2026-08-29T12:04:01Z',
  },
  {
    id: 'quiz_sub_mpsc_polity_3',
    title: 'भारतीय संविधान व राज्यव्यवस्था - सराव चाचणी #3',
    titleMarathi: 'भारतीय संविधान व राज्यव्यवस्था - सराव चाचणी #3',
    description: 'MPSC राज्यसेवा व गट-ब, गट-क अंतर्गत भारतीय संविधान व राज्यव्यवस्था विषयावर आधारित परिपूर्ण TCS/IBPS पॅटर्न चाचणी संच #3.',
    mainCategoryId: 'cat_maha_state',
    mainCategoryName: 'Maharashtra State Exams',
    subCategoryId: 'sub_mpsc',
    subCategoryName: 'MPSC राज्यसेवा व गट-ब, गट-क',
    main_category_id: 'cat_maha_state',
    sub_category_id: 'sub_mpsc',
    examId: 'exam-mpsc',
    examName: 'MPSC',
    category: 'MPSC राज्यसेवा व गट-ब, गट-क',
    access_type: 'paid',
    isFree: false,
    price: 49,
    discountPrice: 99,
    includeInPackage: true,
    durationMinutes: 30,
    totalMarks: 50,
    totalQuestions: 5,
    passingMarks: 20,
    negativeMarking: 0.25,
    difficulty: 'Medium',
    language: 'Marathi',
    rating: 4.8,
    reviewsCount: 165,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=500&q=80',
    type: 'practice',
    questionIds: ['q-10', 'q-3', 'q-15', 'q-6', 'q-7'],
    attemptsCount: 1140,
    createdAt: '2026-08-29T12:04:01Z',
  },

  // 6. Zilla Parishad & Gramsevak
  {
    id: 'quiz_sub_zp_agri_1',
    title: 'ग्रामसेवक कृषी घटक व तंत्रज्ञान - सराव चाचणी #1',
    titleMarathi: 'ग्रामसेवक कृषी घटक व तंत्रज्ञान - सराव चाचणी #1',
    description: 'जिल्हा परिषद व ग्रामसेवक अंतर्गत ग्रामसेवक कृषी घटक व तंत्रज्ञान विषयावर आधारित परिपूर्ण TCS/IBPS पॅटर्न चाचणी संच #1.',
    mainCategoryId: 'cat_maha_state',
    mainCategoryName: 'Maharashtra State Exams',
    subCategoryId: 'sub_zilla_parishad',
    subCategoryName: 'जिल्हा परिषद व ग्रामसेवक',
    main_category_id: 'cat_maha_state',
    sub_category_id: 'sub_zilla_parishad',
    examId: 'exam-maha-gov',
    examName: 'Maharashtra Govt Exams',
    category: 'जिल्हा परिषद व ग्रामसेवक',
    access_type: 'free',
    isFree: true,
    price: 0,
    includeInPackage: true,
    packageName: 'Zilla Parishad & Gramsevak Special Pass',
    durationMinutes: 30,
    totalMarks: 50,
    totalQuestions: 5,
    passingMarks: 20,
    negativeMarking: 0.25,
    difficulty: 'Medium',
    language: 'Marathi',
    rating: 4.9,
    reviewsCount: 135,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=500&q=80',
    type: 'practice',
    questionIds: ['q-10', 'q-6', 'q-9', 'q-1', 'q-2'],
    attemptsCount: 890,
    createdAt: '2026-08-29T12:04:04Z',
  },
  {
    id: 'quiz_sub_zp_agri_3',
    title: 'ग्रामसेवक कृषी घटक व तंत्रज्ञान - सराव चाचणी #3',
    titleMarathi: 'ग्रामसेवक कृषी घटक व तंत्रज्ञान - सराव चाचणी #3',
    description: 'जिल्हा परिषद व ग्रामसेवक अंतर्गत ग्रामसेवक कृषी घटक व तंत्रज्ञान विषयावर आधारित परिपूर्ण TCS/IBPS पॅटर्न चाचणी संच #3.',
    mainCategoryId: 'cat_maha_state',
    mainCategoryName: 'Maharashtra State Exams',
    subCategoryId: 'sub_zilla_parishad',
    subCategoryName: 'जिल्हा परिषद व ग्रामसेवक',
    main_category_id: 'cat_maha_state',
    sub_category_id: 'sub_zilla_parishad',
    examId: 'exam-maha-gov',
    examName: 'Maharashtra Govt Exams',
    category: 'जिल्हा परिषद व ग्रामसेवक',
    access_type: 'paid',
    isFree: false,
    price: 49,
    discountPrice: 99,
    includeInPackage: true,
    durationMinutes: 30,
    totalMarks: 50,
    totalQuestions: 5,
    passingMarks: 20,
    negativeMarking: 0.25,
    difficulty: 'Medium',
    language: 'Marathi',
    rating: 4.8,
    reviewsCount: 165,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=500&q=80',
    type: 'practice',
    questionIds: ['q-10', 'q-6', 'q-9', 'q-3', 'q-4'],
    attemptsCount: 420,
    createdAt: '2026-08-29T12:04:04Z',
  },

  // 7. Bank & Insurance
  {
    id: 'quiz_sub_bank_ibps_1',
    title: 'IBPS PO/Clerk Quantitative Aptitude Mock #1',
    titleMarathi: 'आयबीपीएस बँक भरती संख्यात्मक अभियोग्यता सराव पेपर १',
    description: 'Comprehensive speed math, simplification, data interpretation and arithmetic word problems.',
    mainCategoryId: 'cat_bank_ins',
    mainCategoryName: 'Bank & Insurance',
    subCategoryId: 'sub_bank_ibps_po',
    subCategoryName: 'IBPS PO & Clerk (Prelims + Mains)',
    main_category_id: 'cat_bank_ins',
    sub_category_id: 'sub_bank_ibps_po',
    examId: 'exam-banking',
    examName: 'Banking & Insurance',
    category: 'Bank & Insurance',
    access_type: 'free',
    isFree: true,
    price: 0,
    includeInPackage: true,
    packageName: 'All India Bank Exam Prep Pass',
    durationMinutes: 35,
    totalMarks: 35,
    totalQuestions: 10,
    passingMarks: 15,
    negativeMarking: 0.25,
    difficulty: 'Medium',
    language: 'Bilingual',
    rating: 4.9,
    reviewsCount: 220,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=500&q=80',
    type: 'practice',
    questionIds: ['q-5', 'q-13', 'q-14', 'q-15', 'q-1'],
    attemptsCount: 2400,
    createdAt: '2026-08-29T12:05:00Z',
  },

  // 8. SSC Exams
  {
    id: 'quiz_sub_ssc_cgl_1',
    title: 'SSC CGL Tier-1 General Awareness & Reasoning Mock',
    titleMarathi: 'एसएससी सीजीएल टियर १ सामान्य ज्ञान व बुद्धिमत्ता सराव',
    description: 'High difficulty questions covering General Intelligence, Static GK, Science and Polity for SSC CGL.',
    mainCategoryId: 'cat_ssc',
    mainCategoryName: 'SSC Exams',
    subCategoryId: 'sub_ssc_cgl',
    subCategoryName: 'SSC CGL (Tier 1 & Tier 2)',
    main_category_id: 'cat_ssc',
    sub_category_id: 'sub_ssc_cgl',
    examId: 'exam-ssc',
    examName: 'SSC Exams',
    category: 'SSC Exams',
    access_type: 'free',
    isFree: true,
    price: 0,
    includeInPackage: true,
    packageName: 'SSC Ultimate 2026 Test Series',
    durationMinutes: 60,
    totalMarks: 100,
    totalQuestions: 10,
    passingMarks: 40,
    negativeMarking: 0.5,
    difficulty: 'Medium',
    language: 'Bilingual',
    rating: 4.9,
    reviewsCount: 180,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=500&q=80',
    type: 'practice',
    questionIds: ['q-1', 'q-2', 'q-6', 'q-7', 'q-10'],
    attemptsCount: 1950,
    createdAt: '2026-08-29T12:05:00Z',
  },

  // 9. Railways Exams
  {
    id: 'quiz_sub_rrb_ntpc_1',
    title: 'RRB NTPC CBT-1 General Science & General Awareness Mock #1',
    titleMarathi: 'रेल्वे भरती बोर्ड एनटीपीसी सीबीटी १ सामान्य विज्ञान सराव',
    description: 'Railway Recruitment Board NTPC full syllabus test covering Physics, Chemistry, Biology and History.',
    mainCategoryId: 'cat_railways',
    mainCategoryName: 'Railways Exams',
    subCategoryId: 'sub_rrb_ntpc',
    subCategoryName: 'RRB NTPC (Non-Technical Popular Categories)',
    main_category_id: 'cat_railways',
    sub_category_id: 'sub_rrb_ntpc',
    examId: 'exam-railway',
    examName: 'Railway RRB',
    category: 'Railways Exams',
    access_type: 'free',
    isFree: true,
    price: 0,
    includeInPackage: true,
    packageName: 'Railway RRB NTPC & Group D Super Pass',
    durationMinutes: 90,
    totalMarks: 100,
    totalQuestions: 10,
    passingMarks: 35,
    negativeMarking: 0.33,
    difficulty: 'Medium',
    language: 'Marathi',
    rating: 4.8,
    reviewsCount: 140,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=500&q=80',
    type: 'practice',
    questionIds: ['q-6', 'q-11', 'q-12', 'q-9', 'q-10'],
    attemptsCount: 1600,
    createdAt: '2026-08-29T12:05:00Z',
  },

  // 10. Teaching Exams (MahaTET/TAIT)
  {
    id: 'quiz_sub_mahatet_1',
    title: 'MahaTET Paper 1 बालमानसशास्त्र व अध्यापनशास्त्र Mock #1',
    titleMarathi: 'महाटीईटी पेपर १ बालमानसशास्त्र, मराठी व गणित सराव',
    description: 'Child development and pedagogy with Marathi language practice for Maharashtra Teacher Eligibility Test.',
    mainCategoryId: 'cat_teaching',
    mainCategoryName: 'Teaching Exams',
    subCategoryId: 'sub_maha_tet',
    subCategoryName: 'MahaTET Paper 1 & Paper 2',
    main_category_id: 'cat_teaching',
    sub_category_id: 'sub_maha_tet',
    examId: 'exam-teaching',
    examName: 'TET / TAIT',
    category: 'Teaching Exams',
    access_type: 'free',
    isFree: true,
    price: 0,
    includeInPackage: true,
    packageName: 'Maharashtra Shikshak Bharti MahaTET/TAIT Pass',
    durationMinutes: 60,
    totalMarks: 50,
    totalQuestions: 10,
    passingMarks: 30,
    negativeMarking: 0,
    difficulty: 'Medium',
    language: 'Marathi',
    rating: 4.9,
    reviewsCount: 95,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=500&q=80',
    type: 'practice',
    questionIds: ['q-1', 'q-2', 'q-3', 'q-4', 'q-5'],
    attemptsCount: 880,
    createdAt: '2026-08-29T12:05:00Z',
  },

  // 11. Subject-Wise & Special Tests
  {
    id: 'quiz_sub_special_marathi_1',
    title: 'मराठी व्याकरण विशेष: समास, प्रयोग व संधी स्पेशल टेस्ट',
    titleMarathi: 'मराठी व्याकरण विशेष: समास, प्रयोग व संधी स्पेशल टेस्ट',
    description: 'स्पर्धा परीक्षांसाठी १००% खात्रीशीर मराठी व्याकरण गुणांसाठी विशेष सराव चाचणी.',
    mainCategoryId: 'cat_subject_special',
    mainCategoryName: 'Subject-Wise & Special Test',
    subCategoryId: 'sub_special_marathi',
    subCategoryName: 'मराठी व्याकरण व शब्दसंग्रह स्पेशल',
    main_category_id: 'cat_subject_special',
    sub_category_id: 'sub_special_marathi',
    examId: 'exam-mpsc',
    examName: 'Subject-Wise Special',
    category: 'Subject-Wise & Special Test',
    access_type: 'free',
    isFree: true,
    price: 0,
    includeInPackage: true,
    durationMinutes: 20,
    totalMarks: 30,
    totalQuestions: 5,
    passingMarks: 15,
    negativeMarking: 0.25,
    difficulty: 'Medium',
    language: 'Marathi',
    rating: 5.0,
    reviewsCount: 260,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=500&q=80',
    type: 'practice',
    questionIds: ['q-1', 'q-2', 'q-3', 'q-4', 'q-5'],
    attemptsCount: 3400,
    createdAt: '2026-08-29T12:05:00Z',
  },
  {
    id: 'quiz_sub_special_polity_1',
    title: 'भारतीय राज्यघटना व पंचायतराज कलमे स्पेशल टेस्ट (Paid Individual)',
    titleMarathi: 'भारतीय राज्यघटना व पंचायतराज कलमे स्पेशल टेस्ट',
    description: 'महत्त्वाची कलमे, घटनादुरुस्त्या व सर्वोच्च न्यायालय ऐतिहासिक निवाडे विशेष सराव.',
    mainCategoryId: 'cat_subject_special',
    mainCategoryName: 'Subject-Wise & Special Test',
    subCategoryId: 'sub_special_polity',
    subCategoryName: 'भारतीय संविधान, पंचायत राज व पोलीस कायदा',
    main_category_id: 'cat_subject_special',
    sub_category_id: 'sub_special_polity',
    examId: 'exam-mpsc',
    examName: 'Subject-Wise Special',
    category: 'Subject-Wise & Special Test',
    access_type: 'paid',
    isFree: false,
    price: 29,
    discountPrice: 59,
    includeInPackage: false,
    durationMinutes: 25,
    totalMarks: 40,
    totalQuestions: 5,
    passingMarks: 20,
    negativeMarking: 0.25,
    difficulty: 'MPSC Level',
    language: 'Marathi',
    rating: 4.9,
    reviewsCount: 190,
    status: 'published',
    thumbnail: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=500&q=80',
    type: 'practice',
    questionIds: ['q-10', 'q-3', 'q-15', 'q-6', 'q-9'],
    attemptsCount: 1250,
    createdAt: '2026-08-29T12:05:00Z',
  },
];
