import re

file_path = r'a:\Projects\mission_vardi_app\mock_test_portal\src\app\page.tsx'
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    '🎉 लॉगिन यशस्वी! स्वागत आहे, ${u.name || "विद्यार्थी"}!': '🎉 Login successful! Welcome, ${u.name || "Student"}!',
    'लॉगिन अयशस्वी झाले. कृपया ईमेल आणि पासवर्ड तपासा.': 'Login failed. Please check your email and password.',
    '🎉 रजिस्ट्रेशन यशस्वी! स्वागत आहे, ${u.name}! आता तुम्ही लीडरबोर्ड व फिजिकल चाचणी वापरू शकता.': '🎉 Registration successful! Welcome, ${u.name}! You can now use the leaderboard and physical tests.',
    'रजिस्ट्रेशन अयशस्वी झाले. कृपया पुन्हा प्रयत्न करा.': 'Registration failed. Please try again.',
    '✓ प्रोफाईल आणि जिल्हा माहिती यशस्वीरित्या अपडेट झाली!': '✓ Profile and district information updated successfully!',
    'कृपया शारीरिक चाचणीची नोंद करण्यासाठी प्रथम लॉगिन करा!': 'Please login first to submit your physical test record!',
    '🎉 आजची शारीरिक चाचणी नोंद यशस्वीरित्या सेव्ह झाली!': '🎉 Today\'s physical test record saved successfully!',
    'नोंद सेव्ह करताना समस्या आली. कृपया पुन्हा प्रयत्न करा.': 'Problem saving record. Please try again.',
    'माहिती लोड होत आहे...': 'Loading information...',
    '⚙️ माझे प्रोफाईल': '⚙️ My Profile',
    '🔑 विद्यार्थी लॉगिन / रजिस्ट्रेशन (Join Leaderboard)': '🔑 Student Login / Register (Join Leaderboard)',
    'महत्त्वाचे अपडेट': 'Important Update',
    '📝 सराव Exam': '📝 Mock Exams',
    '📚 स्टडी मटेरियल व नोट्स': '📚 Study Materials & Notes',
    '📜 मागील प्रश्नपत्रिका': '📜 Previous Year Papers',
    '🏆 टॉपर लीडरबोर्ड': '🏆 Top Leaderboard',
    '🏃 शारीरिक चाचणी (Physical Fitness)': '🏃 Physical Fitness',
    '👤 माझे प्रोफाईल (Profile)': '👤 My Profile',
    '📋 उपलब्ध मोफत सराव Exam (Available Free Mock Tests)': '📋 Available Free Mock Tests',
    'तुमच्या इच्छित परीक्षेची निवड करा आणि लगेच ऑनलाइन टेस्ट सोडवायला सुरुवात करा.': 'Select your desired exam and start solving the online test instantly.',
    'एकूण {filteredTests.length} टेस्ट उपलब्ध': 'Total {filteredTests.length} tests available',
    '🔥 सर्व Exam (All Exams)': '🔥 All Exams',
    'कोणतीही Exam सापडली नाही!': 'No Exam Found!',
    'सध्या या विभागामध्ये कोणतीही लाईव्ह टेस्ट उपलब्ध नाही किंवा वेगळा शब्द शोधून पहा.': 'Currently no live test available in this section or try searching a different word.',
    '🔄 सर्व Exam पहा (View All)': '🔄 View All Exams',
    '📚 स्टडी मटेरियल, चालू घडामोडी व व्याकरण नोट्स (Live Notes)': '📚 Study Materials, Current Affairs & Grammar Notes (Live Notes)',
    'परीक्षेसाठी अत्यंत उपयुक्त अशा सविस्तर नोट्स आणि स्टडी मटेरियल मोफत वाचा.': 'Read detailed notes and study materials for exams for free.',
    'सध्या कोणत्याही नोट्स उपलब्ध नाहीत': 'Currently no notes available',
    'लवकरच नवीन नोट्स जोडल्या जातील.': 'New notes will be added soon.',
    '📖 संपूर्ण नोट्स वाचा (Read Note)': '📖 Read Complete Note',
    '📜 मागील वर्षांच्या प्रश्नपत्रिका (Previous Year Question Papers - PYQ)': '📜 Previous Year Question Papers (PYQ)',
    'Competitive Exams व इतर स्पर्धा Examंमध्ये विचारल्या गेलेल्या जुन्या प्रश्नपत्रिका आणि त्यांची उत्तरे.': 'Old question papers and answers asked in Competitive Exams and other competitive exams.',
    'सध्या जुन्या प्रश्नपत्रिका लोड होत आहेत': 'Currently old question papers are loading',
    'लवकरच सर्व मागील प्रश्नपत्रिका डाउनलोडसाठी उपलब्ध होतील.': 'All previous question papers will be available for download soon.',
    'वर्ष:': 'Year:',
    '📥 पेपर डाउनलोड करा (Download PDF)': '📥 Download Paper (PDF)',
    'ही प्रश्नपत्रिका लवकरच PDF स्वरूपात उपलब्ध होईल!': 'This question paper will be available in PDF format soon!',
    '📄 प्रश्नपत्रिका पहा': '📄 View Question Paper',
    '🌟 लीडरबोर्डमध्ये तुमचे नाव पाहायचे आहे का?': '🌟 Do you want to see your name in the leaderboard?',
    'स्वागत आहे, ${currentUser.name}! तुमचे प्रोफाईल यशस्वीरित्या जोडले गेले आहे. ऑनलाइन सराव Exam सोडवा आणि जास्त गुण मिळवून लीडरबोर्डच्या टॉपवर या!': 'Welcome, ${currentUser.name}! Your profile has been successfully added. Take online mock exams, score high, and top the leaderboard!',
    'जर तुम्हाला तुमचे नाव या ग्लोबल लीडरबोर्डमध्ये पाहायचे असेल, तर लगेच लॉगिन किंवा मोफत रजिस्ट्रेशन करा आणि तुमचे प्रोफाईल अपडेट करा. सराव Exam सोडवून तुमचे गुण लगेच लीडरबोर्डवर दिसतील!': 'If you want to see your name in this global leaderboard, login or register for free now and update your profile. Take mock exams and your scores will immediately appear on the leaderboard!',
    '✏️ प्रोफाईल व जिल्हा संपादित करा': '✏️ Edit Profile & District',
    '🔑 लॉगिन / रजिस्ट्रेशन करा (Login Now)': '🔑 Login / Register Now',
    '🏆 ग्लोबल टॉपर लीडरबोर्ड (Global Top Aspirants)': '🏆 Global Top Aspirants Leaderboard',
    'मिशन वर्दी ॲप व वेब पोर्टलवरील सर्वाधिक गुण मिळवणारे Globalातील टॉप विद्यार्थी!': 'Top students from EduSaaS app and web portal with the highest scores!',
    'लीडरबोर्ड रँकिंग लोड होत आहे...': 'Loading leaderboard ranking...',
    'रँक (Rank)': 'Rank',
    'विद्यार्थ्याचे नाव (Aspirant Name)': 'Aspirant Name',
    'जिल्हा (District)': 'District',
    'एकूण गुण (Points)': 'Total Points',
    'अनामिक विद्यार्थी': 'Anonymous Student',
    'तुम्ही (You)': 'You',
    '🏃 Global Competitive Exams शारीरिक चाचणी ट्रॅकर (Physical Fitness Guide & Logs)': '🏃 Global Competitive Exams Physical Test Tracker',
    '१६०० मीटर धावणे, १०० मीटर धावणे व गोळाफेक चाचणीचे गुण मोजा आणि तुमच्या रोजच्या सराव चाचणीच्या नोंदी ठेवा.': 'Calculate your scores for 1600m run, 100m run, and shot put and keep a record of your daily practice tests.',
    '🎯 शारीरिक चाचणी गुण गणक (Marks Calculator)': '🎯 Physical Test Marks Calculator',
    '१. १६०० मीटर धावणे (1600m Running - 20 Marks):': '1. 1600m Running (20 Marks):',
    'मिनिटे (Min):': 'Minutes (Min):',
    'सेकंद (Sec):': 'Seconds (Sec):',
    '२. १०० मीटर धावणे (100m Running - 15 Marks):': '2. 100m Running (15 Marks):',
    'सेकंद (Sec e.g. 11.5):': 'Seconds (Sec e.g. 11.5):',
    '३. गोळाफेक (Shot Put - 15 Marks):': '3. Shot Put (15 Marks):',
    'अंतर मीटरमध्ये (Meters e.g. 8.50):': 'Distance in Meters (e.g. 8.50):',
    '📝 आजच्या सरावाची टीप (Notes/Ground location):': '📝 Today\'s practice note (Notes/Ground location):',
    'उदा. सकाळी ६ वाजता शिवाजी स्टेडियमवर सराव': 'e.g. Practice at Shivaji Stadium at 6 AM',
    '१६००मी गुण:': '1600m Marks:',
    '१००मी गुण:': '100m Marks:',
    'गोळा गुण:': 'Shot Put Marks:',
    'तुमचे अंदाजे एकूण शारीरिक गुण: ': 'Your estimated total physical marks: ',
    'सेव्ह होत आहे...': 'Saving...',
    '➕ आजची शारीरिक चाचणी नोंद सेव्ह करा (Save Log)': '➕ Save Today\'s Physical Test Log',
    '🔒 सेव्ह करण्यासाठी प्रथम लॉगिन करा': '🔒 Login first to save',
    '📊 तुमची शारीरिक प्रगती व नोंदी (History)': '📊 Your Physical Progress & History',
    'नोंदी': 'Logs',
    'तुमचा सराव इतिहास पाहण्यासाठी लॉगिन करा': 'Login to view your practice history',
    'लॉगिन केल्यानंतर तुम्ही दररोज केलेल्या धावणे व गोळाफेक सरावाच्या सर्व नोंदी येथे सुरक्षित राहतील.': 'After logging in, all your daily running and shot put practice logs will be safely stored here.',
    '🔑 लगेच लॉगिन करा (Login Now)': '🔑 Login Now',
    'अद्याप कोणतीही शारीरिक नोंद केलेली नाही': 'No physical logs recorded yet',
    'डावीकडील गणक वापरून तुमची पहिली शारीरिक चाचणी नोंद सेव्ह करा!': 'Use the calculator on the left to save your first physical test log!',
    '📅 दिनांक: ': '📅 Date: ',
    'आज': 'Today',
    'ही नोंद डिलीट करायची आहे का?': 'Do you want to delete this log?',
    '🗑️ डिलीट': '🗑️ Delete',
    '🏃 १६००मी:': '🏃 1600m:',
    'मि': 'Min',
    'से': 'Sec',
    '⚡ १००मी:': '⚡ 100m:',
    'सेकंद': 'Seconds',
    '🤾 गोळा:': '🤾 Shot Put:',
    'मी': 'm',
    'तुमचे वैयक्तिक स्टडी प्रोफाईल (User Profile Hub)': 'Your Personal Study Profile (User Profile Hub)',
    'मोबाईल ॲपप्रमाणेच तुमचे लीडरबोर्ड रँकिंग, सराव Examंचे गुण आणि शारीरिक चाचणीच्या सर्व नोंदी एकाच ठिकाणी पाहण्यासाठी कृपया खात्यात प्रवेश करा किंवा मोफत नोंदणी करा.': 'Just like the mobile app, login or register for free to see your leaderboard ranking, mock exam scores, and physical test logs all in one place.',
    '🔑 खात्यात लॉगिन करा (Login Now)': '🔑 Login to Account (Login Now)',
    '📝 मोफत नवीन नोंदणी (Free Register)': '📝 Free Registration (Register)',
    'जिल्हा:': 'District:',
    '🎯 Global पोलीस व Aptitude Tests भरती उमेदवार': '🎯 Global Police & Aptitude Tests Aspirant',
    '✏️ माहिती व जिल्हा संपादित करा': '✏️ Edit Info & District',
    '🚪 लॉग आउट करा': '🚪 Logout',
    'लीडरबोर्ड स्थिती (Leaderboard)': 'Leaderboard Status',
    'रँक': 'Rank',
    'सहभागी व्हा': 'Participate',
    'टॉप १० मध्ये तुमची रँक': 'Your rank in Top 10',
    'सराव Exam सोडवून गुण मिळवा': 'Solve mock exams and earn points',
    'शारीरिक चाचणी नोंदी (Fitness Logs)': 'Physical Test Logs (Fitness Logs)',
    'सर्वोच्च गुण:': 'Highest Score:',
    'सराव Exam (Mock Tests)': 'Mock Exams (Mock Tests)',
    'टेस्ट उपलब्ध': 'Tests Available',
    'TCS / IBPS पॅटर्ननुसार नियमित सराव': 'Regular practice according to TCS / IBPS pattern',
    '📜 माझी शारीरिक चाचणी प्रगती (Fitness Activity History)': '📜 My Physical Test Progress (Fitness Activity History)',
    'तुमच्या रोजच्या १६०० मीटर, १०० मीटर व गोळाफेक सरावाच्या नोंदी.': 'Logs of your daily 1600m, 100m running and shot put practice.',
    '➕ नवीन शारीरिक चाचणी नोंद करा ➡': '➕ Add New Physical Test Log ➡',
    'अद्याप एकही शारीरिक चाचणी नोंद नाही': 'No physical test logs yet',
    'तुमची रोजची धावण्याची वेळ आणि गोळाफेक अंतर मोजा आणि येथे सेव्ह करा.': 'Measure your daily running time and shot put distance and save it here.',
    '🏃 गुण मोजा आणि नोंद सेव्ह करा': '🏃 Calculate Marks and Save Log',
    'तारीख (Date)': 'Date',
    '१६०० मीटर (वेळ व गुण)': '1600m (Time & Marks)',
    '१०० मीटर (वेळ व गुण)': '100m (Time & Marks)',
    'गोळाफेक (अंतर व गुण)': 'Shot Put (Distance & Marks)',
    'एकूण गुण (Total)': 'Total Marks',
    'गुण': 'Marks',
    'या नोट्सचा सविस्तर मजकूर लवकरच अपडेट केला जाईल.': 'The detailed content of these notes will be updated soon.',
    '✓ बंद करा (Close)': '✓ Close',
    'स्वागत आहे! (Welcome Back)': 'Welcome Back!',
    'मोफत नोंदणी (Create Account)': 'Free Registration (Create Account)',
    'माझे प्रोफाईल (Edit Profile)': 'My Profile (Edit Profile)',
    'तुमच्या खात्यात लॉगिन करा आणि सराव सुरू करा.': 'Login to your account and start practicing.',
    'केवळ १ मिनिटात तुमची नोंदणी पूर्ण करा आणि लीडरबोर्डवर या.': 'Complete your registration in just 1 minute and get on the leaderboard.',
    'तुमचे नाव व जिल्हा लीडरबोर्डसाठी अपडेट ठेवा.': 'Keep your name and district updated for the leaderboard.',
    '🔑 लॉगिन (Login)': '🔑 Login',
    '📝 नवीन नोंदणी (Register)': '📝 Register',
    '📧 ईमेल पत्ता (Email):': '📧 Email Address:',
    '🔒 पासवर्ड (Password):': '🔒 Password:',
    'लॉगिन होत आहे...': 'Logging in...',
    '🔑 खात्यात प्रवेश करा (Login Now)': '🔑 Access Account (Login Now)',
    'खाते नाही?': 'Don\'t have an account?',
    'मोफत नवीन खाते उघडा ➡': 'Create new free account ➡',
    '👤 पूर्ण नाव (Full Name):': '👤 Full Name:',
    'उदा. राहुल शर्मा': 'e.g. Rahul Sharma',
    '🔒 पासवर्ड तयार करा (Password):': '🔒 Create Password:',
    'कमीत कमी ६ अक्षरे': 'Minimum 6 characters',
    '📱 मोबाईल नंबर (Optional):': '📱 Mobile Number (Optional):',
    '📍 जिल्हा (District) *:': '📍 District *:',
    'उदा. पुणे': 'e.g. Pune',
    'रजिस्ट्रेशन होत आहे...': 'Registering...',
    '✓ मोफत नोंदणी करा (Register Now)': '✓ Register for Free (Register Now)',
    'आधीच खाते आहे?': 'Already have an account?',
    'लॉगिन करा ➡': 'Login ➡',
    '👤 तुमचे नाव (Name):': '👤 Your Name:',
    '📍 तुमचा जिल्हा (District for Leaderboard) *:': '📍 Your District (For Leaderboard) *:',
    'अपडेट होत आहे...': 'Updating...',
    '✓ बदल सेव्ह करा (Save Profile)': '✓ Save Changes (Save Profile)',
    '🚪 लॉग आउट करा (Logout)': '🚪 Logout',
    '🏆 Global स्पर्धा Exam तयारी (Exam Categories Overview)': '🏆 Global Competitive Exams Prep (Exam Categories Overview)',
    'मिशन वर्दी': 'EduSaaS',
    'स्टडी पोर्टल': 'Study Portal',
    'Globalातील लाखो विद्यार्थ्यांसोबत स्पर्धा करा, तुमचे गुण तपासा आणि वर्दीचे स्वप्न साकार करा!': 'Compete with lakhs of students globally, check your scores, and achieve your dreams!',
    'ग्लोबल लीडरबोर्ड रँकिंग': 'Global Leaderboard Ranking',
    'Globalातील टॉप विद्यार्थ्यांमध्ये तुमचे नाव पहा': 'See your name among the top students globally',
    'फिजिकल चाचणी गुण गणक': 'Physical Test Marks Calculator',
    '५० पैकी तुमचे शारीरिक चाचणी गुण लगेच मोजा': 'Instantly calculate your physical test marks out of 50',
    '१००% मोफत सराव Exam': '100% Free Mock Exams',
    'TCS / IBPS पॅटर्ननुसार दररोज नवीन टेस्ट': 'New tests daily based on TCS / IBPS pattern',
    '🔒 सुरक्षित व खात्रीशीर • १ लाख+ विद्यार्थ्यांचा विश्वास': '🔒 Secure & Trusted • Trusted by 1 Lakh+ Students',
    'नियमित सराव चाचणी': 'Regular practice test',
    'शारीरिक चाचणी (Physical Fitness)': 'Physical Fitness',
    'माझे प्रोफाईल (Profile)': 'My Profile',
    '🇮🇳 Global पोलीस व Aptitude Tests भरती': '🇮🇳 Global Police & Aptitude Tests Prep',
    'विद्यार्थी': 'Student'
}

for k, v in replacements.items():
    content = content.replace(k, v)

# additional generic replaces for numbers
content = re.sub(r'([१२३४५६७८९०]+)', lambda m: ''.join(str('०१२३४५६७८९'.index(c)) for c in m.group(1)), content)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)
print("done")
